<img src="https://images.efollett.com/htmlroot/images/templates/storeLogos/CA/864.gif" style="float: right;"> 




# ECON611
### Lecture 10 -  Numpy - Introduction.
- Notes adapted from: 

    1. [Numpy.org](https://numpy.org/)
    2. [Numpy Tutorial for Beginners](https://www.kaggle.com/orhansertkaya/numpy-tutorial-for-beginners) 

## <span style="color:blue">WHAT IS NUMPY</span>
---
- Numerical Python.
- Scientific computing with Python.
- Python library that provides a multidimensional array object.
    - arrays and matrices.
    - mathematical, logical, shape manipulation, sorting, selecting.
    - linear algebra, simulation, statistics
    
    
    
- Differences between NumPy arrays and the standard Python sequences:
    - NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). 
    - Changing the size of an ndarray will create a new array and delete the original.
    - The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.
    - NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
    - A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. ***In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.***   

## <span style="color:blue">WHY IS NUMPY</span>
---
- Fast: Behind the scenes it uses Vectorization:
    - Vectorization describes the absence of any explicit looping, indexing, etc., in the code - these things are taking place, of course, just “behind the scenes” in optimized, pre-compiled ```C``` code. 
    
```
1. Vectorized code is more concise and easier to read.
2. Fewer lines of code generally means fewer bugs.
3. The code more closely resembles standard mathematical notation (making it easier, typically, to correctly code mathematical constructs)
4. Vectorization results in more “Pythonic” code. Without vectorization, our code would be littered with inefficient and difficult to read for loops.
 ```
 
```
Did you know that some of python’s leading package rely on NumPy as a fundamental piece of their infrastructure (examples include scikit-learn, SciPy, pandas, and tensorflow). Beyond the ability to slice and dice numeric data, mastering numpy will give you an edge when dealing and debugging with advanced usecases in these libraries.
```

In [83]:
'''How to import it into your workflow'''
import numpy as np

In [129]:
'''
Array
1. Homogeneous multidimensional array
2. It is a table with same type elements, i.e, integers or string or characters (homogeneous), usually integers. 
3. In NumPy, dimensions are called axes. 
4. The number of axes is called the rank.
'''
print(np.array([1,2,3])) 
print(np.array([1,2,3]).shape) ## 3 rows and 1 column

[1 2 3]
(3,)


## <span style="color:blue">Graphically</span> 
---
<p align="center">
  <img src="../../img/np_array_1.png" width="600" height="1000">
</p>

In [85]:
'''
Allow Numpy to initialize the values:
1. Ones
2. Zeros
3. random.random()
'''
print(np.ones(3))
print(np.zeros(3))
print(np.random.random(3))

[ 1.  1.  1.]
[ 0.  0.  0.]
[ 0.51898884  0.66197782  0.87979172]


## <span style="color:blue">Graphically</span> 
---
<p align="center">
  <img src="../../img/np_array_2.png" width="600" height="1000">
</p>

# <span style="color:blue">Mathematics</span> 
---
- Array - one dimension vector 

In [130]:
data = np.array([1,2]) 
ones =  np.ones(2)
print(data, ones)
print(data.shape, ones.shape)

[1 2] [ 1.  1.]
(2,) (2,)


In [87]:
'''
    Adding them up - position wise
'''
print(data + ones)



''' Substraction'''
print(data - ones)


'''Multiplication'''
print(data*data)

'''Division'''
print(data/data)

'''Vector and Scalar Multiplication'''
print(data*1.6)

[ 2.  3.]
[ 0.  1.]
[1 4]
[ 1.  1.]
[ 1.6  3.2]


## <span style="color:blue">Graphically</span> 
---
<p align="center">
  <img src="../../img/np_array_3.png" width="400" height="1000">
</p>
<p align="center">
  <img src="../../img/np_array_4.png" width="700" height="1000">
</p>
<p align="center">
  <img src="../../img/np_array_5.png" width="700" height="1000">
</p>

In [88]:
'''INDEXING: Accesing elements of an array'''
data = np.array([1,2,3])
print(data)

print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])

[1 2 3]
1
2
[1 2]
[2 3]


In [89]:
'''AGGREGATION'''
print(data)
print(data.max())
print(data.min())
print(data.sum())
print(data.mean())
print(data.prod())
print(data.std())
print(data.argmin()) #index of min value
print(data.argmax()) #index of max value

[1 2 3]
3
1
6
2.0
6
0.816496580928
0
2


## <span style="color:blue">Graphically</span> 
---
<p align="center">
  <img src="../../img/np_array_6.png" width="800" height="1000">
</p>

## <span style="color:blue">More on Aggregation</span> 
---
<p align="center">
  <img src="../../img/np_array_7.png" width="500" height="1000">
</p>

## <span style="color:blue">Adding Dimensions - Matrix</span> 
---
- Use a lists of lists

In [90]:
print(np.array([[1,2], [3,4]]))
print("Shape: ", np.array([[1,2], [3,4]]).shape)
print("\n")

print(np.ones((3,2)))
print("Shape: ", (np.ones((3,2)).shape))
print("\n")

print(np.zeros((3,2), dtype=int))
print("Shape: ", (np.zeros((3,2)).shape))
print("\n")

print(np.random.random((3,2)))
print("Shape: ", (np.random.random((3,2)).shape))
print("\n")

[[1 2]
 [3 4]]
Shape:  (2, 2)


[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
Shape:  (3, 2)


[[0 0]
 [0 0]
 [0 0]]
Shape:  (3, 2)


[[ 0.98939944  0.46201437]
 [ 0.00461663  0.80096434]
 [ 0.6253768   0.8495485 ]]
Shape:  (3, 2)




## <span style="color:blue">Graphically</span> 
---
<p align="center">
  <img src="../../img/np_array_8.png" width="400" height="1000">
</p>
<p align="center">
  <img src="../../img/np_array_9.png" width="700" height="1000">
</p>


## <span style="color:blue">Matrix - Arithmetic</span> 
---
- As long as the size of the matrix are of the same size, one can implement mathematical operations.

```python
data = np.array([[1,2], [3,4]])
ones = np.ones((2,2))

print("sum")
print(data+ones)

print("subst")
print(data-ones)

print("mult")
print(data*ones)

print("div")
print(data/ones)

```

In [91]:
data = np.array([[1,2], [3,4]])
print(data)
print(data.shape)
print("\n")

ones = np.ones((2,2))
print(ones)
print(ones.shape)
print("\n")

print("sum")
print(data+ones)
print("\n")

print("subst")
print(data-ones)
print("\n")

print("mult")
print(data*ones)
print("\n")

print("div")
print(data/ones)
print("\n")

[[1 2]
 [3 4]]
(2, 2)


[[ 1.  1.]
 [ 1.  1.]]
(2, 2)


sum
[[ 2.  3.]
 [ 4.  5.]]


subst
[[ 0.  1.]
 [ 2.  3.]]


mult
[[ 1.  2.]
 [ 3.  4.]]


div
[[ 1.  2.]
 [ 3.  4.]]




## <span style="color:blue">Matrix - Arithmetic</span> 
---
- If dealing with matrices of different size, as long as the different dimension is one 
    (e.g. the matrix has only one column or one row), in which case NumPy uses 
    its broadcast rules for that operation
    
```python
data = np.array([[1,2], [3,4], [5,6]])

ones_row = np.ones((1,2))

data +ones_row

```

In [92]:
data = np.array([[1,2], [3,4], [5,6]])
print(data)
print(data.shape)
print("\n")

ones_row = np.ones((1,2))
print(ones_row)
print(ones_row.shape)
print("\n")

print(data +ones_row)
print((data +ones_row).shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


[[ 1.  1.]]
(1, 2)


[[ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]]
(3, 2)


## <span style="color:blue">Matrix - Dot Product</span> 
---
- Sum of the products of the corresponding entries of the two sequences of numbers.


In [93]:
data = np.array([1, 2, 3])
print(data.shape)
print("\n")

powers_ten =np.array([ [1,10], [100, 1000], [10000, 100000] ])
print(powers_ten.shape)
print("\n")

print(np.dot(data, powers_ten))
print(np.dot(data, powers_ten).shape)

(3,)


(3, 2)


[ 30201 302010]
(2,)


## <span style="color:blue">Graphically</span> 
---
<p align="center">
  <img src="../../img/np_array_10.png" width="500" height="1000">
</p>
<p align="center">
  <img src="../../img/np_array_11.png" width="700" height="1000">
</p>

## <span style="color:blue">Matrix - Indexing</span> 
---


In [110]:
data = np.array([[1,2], [3,4], [5,6]])
print(data)
print("\n")

print(data[0,1]) #top right value
print("\n")

print(data[1:]) ## one can add 3
print("\n")

print(data[0:2, 0])


[[1 2]
 [3 4]
 [5 6]]


2


[[3 4]
 [5 6]]


[1 3]


## <span style="color:blue">Matrix - Aggregation</span> 
---


In [113]:
'''AGGREGATION'''
print(data)
print(data.max())
print(data.min())
print(data.sum())
print(data.mean())
print(data.prod())
print(data.std())
print(data.argmin()) #index of min value
print(data.argmax()) #index of max value

[[1 2]
 [3 4]
 [5 6]]
6
1
21
3.5
720
1.70782512766
0
5


## <span style="color:blue">Matrix - Aggregation</span> 
---
- By colums => axis= 0
- By rows => axiis = 1

In [114]:
print(data)
print("\n")
print(data.max(axis=0))
print("\n")
print(data.min(axis=0))
print("\n")
print(data.sum(axis=0))
print("\n")
print(data.mean(axis=0))
print("\n")
print(data.prod(axis=0))
print("\n")
print(data.std(axis=0))
print("\n")
print(data.argmin(axis=0)) #index of min value
print("\n")
print(data.argmax(axis=0)) #index of max value
print("\n")

[[1 2]
 [3 4]
 [5 6]]


[5 6]


[1 2]


[ 9 12]


[ 3.  4.]


[15 48]


[ 1.63299316  1.63299316]


[0 0]


[2 2]




In [115]:
print(data)
print("\n")
print(data.max(axis=1))
print("\n")
print(data.min(axis=1))
print("\n")
print(data.sum(axis=1))
print("\n")
print(data.mean(axis=1))
print("\n")
print(data.prod(axis=1))
print("\n")
print(data.std(axis=1))
print("\n")
print(data.argmin(axis=1)) #index of min value
print("\n")
print(data.argmax(axis=1)) #index of max value
print("\n")

[[1 2]
 [3 4]
 [5 6]]


[2 4 6]


[1 3 5]


[ 3  7 11]


[ 1.5  3.5  5.5]


[ 2 12 30]


[ 0.5  0.5  0.5]


[0 0 0]


[1 1 1]




## <span style="color:blue">Matrix - Transposing & Reshaping</span> 
---
- This is helpful when we need to take the ```dot``` product of two matrices and need to align the dimension they share. 

In [120]:
print(data)
print(data.shape)
print("\n")
print(data.T)
print(data.T.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


[[1 3 5]
 [2 4 6]]
(2, 3)


In [126]:
data = np.array([ [1], [2], [3], [4], [5], [6] ])
print(data)
print(data.shape)
print("\n")
print(data.reshape(2,3))
print("\n")
print(data.reshape(3,2))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


[[1 2 3]
 [4 5 6]]


[[1 2]
 [3 4]
 [5 6]]


## <span style="color:blue">Graphically</span> 
---
<p align="center">
  <img src="../../img/np_array_12.png" width="600" height="1000">
</p>

<p align="center">
  <img src="../../img/stop_pict.jpg" width="400" height="800">
</p>